### ISSUE TITLE
ошибочное срабатывание

### ISSUE THREAD

**Issue by mixa999999** [UnrealKaraulov/UnrealCheatFinderDB#1]
Привет, в отчете следующий текст

> Найдено 2 следов установленных читов!
> Найден чит Alternative 2024 [DATA 4]! Вероятная дата установки: 07/02/2024 17:47:48.
> Были найдены недавно переименованные процессы, убедитесь что это не чит лоадеры:
> C:\program files\oxygen xml author 26\oxygenauthor26.1.exe

При этом никаких читов на компе нет, но есть желание разобраться в ситуации, на что именно сработал данный детект.
Прикладываю полный архив с отчетом
[report.zip](https://github.com/user-attachments/files/18189085/report.zip)

**Comment by UnrealKaraulov** [comment]
@mixa999999 да дата обнаружения Alternative 2024 [DATA 4] указывает на то что этого файла еще не могло быть, ищет по файлу settings без расширения в папке APPDATA, будет исправлено через полчаса, спасибо за баг репорт.
